### ISSUE TITLE
Published JAR with Releases

### ISSUE THREAD

**Issue by mgramigna** [cqframework/cql-language-server#62]
Is it possible to include the `shaded` .jar file along with the GitHub releases? Currently, it seems like the only way to get the jar for use in editors other than VS Code is to download the source code and build it yourself.

I'm a neovim user, which has capabilities to hook up to language servers. The cql-language-server works well, but setup would be a lot easier if the jar could just be downloaded from the releases directly for those who just want to consume it rather than develop on it.

If there is an obvious way to get the jar via some other hosted repository, please let me know. Thanks!

**Comment by JPercival** [comment]
Hi @mgramigna, the shaded jar is the `service` artifact:
https://search.maven.org/artifact/org.opencds.cqf.cql.ls/cql-ls-service/2.0.0/jar
